plugins {
    id 'com.android.application'
}

android {
    namespace 'com.latinbot.sugo'
    compileSdk 34 // O la versión que tengas configurada

    defaultConfig {
        applicationId "com.latinbot.sugo"
        minSdk 24
        targetSdk 33
        
        // --- CÓDIGO DE AUTO-ACTUALIZACIÓN CORREGIDO ---
        def timeVersion = (int) (System.currentTimeMillis() / 10000)
        versionCode timeVersion
        versionName "1.0." + timeVersion
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}