plugins {
    id 'com.android.application'
}

android {
    namespace 'com.latinbot.sugo'
    compileSdk 34 // O la versión que tengas configurada

    defaultConfig {
        applicationId "com.latinbot.sugo"
        minSdk 24
        targetSdk 33
        
        // --- CÓDIGO DE AUTO-ACTUALIZACIÓN ---
        versionCode (System.currentTimeMillis() / 10000).toInteger()
        versionName "1.0." + (System.currentTimeMillis() / 10000).toInteger()
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}